version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: flavorai-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: flavorai
      POSTGRES_PASSWORD: flavorai
      POSTGRES_DB: flavorai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
